---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-vardemo-pvc
  namespace: vardemo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
