---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-vardemo-pvc
  namespace: vardemo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
